name: {{cookiecutter.repo_name}}
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - asn1crypto=0.24.0
  - atomicwrites=1.3.0
  - attrs=19.2.0
  - blinker=1.4
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - cachetools=2.1.0
  - certifi=2019.9.11
  - cffi=1.12.3
  - chardet=3.0.4
  - cloudpickle=1.2.2
  - cryptography=2.7
  - cycler=0.10.0
  - cytoolz=0.10.0
  - dask-core=2.5.0
  - decorator=4.4.0
  - freetype=2.10.0
  - fsspec=0.5.1
  - gcsfs=0.3.0
  - google-auth=1.6.3
  - google-auth-oauthlib=0.4.0
  - icu=64.2
  - idna=2.8
  - imageio=2.5.0
  - importlib_metadata=0.23
  - joblib=0.14.0
  - jpeg=9c
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - lz4-c=1.8.3
  - matplotlib-base=3.1.1
  - more-itertools=7.2.0
  - ncurses=6.1
  - networkx=2.3
  - numpy=1.17.2
  - oauthlib=3.0.1
  - olefile=0.46
  - openssl=1.1.1c
  - packaging=19.2
  - pandas=0.25.1
  - pillow=6.2.0
  - pip=19.2.3
  - pluggy=0.13.0
  - py=1.8.0
  - pyasn1=0.4.6
  - pyasn1-modules=0.2.6
  - pycparser=2.19
  - pyjwt=1.7.1
  - pyopenssl=19.0.0
  - pyparsing=2.4.2
  - pysocks=1.7.1
  - pytest=5.0.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pywavelets=1.0.3
  - readline=8.0
  - requests=2.22.0
  - requests-oauthlib=1.2.0
  - rsa=3.4.2
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - setuptools=41.2.0
  - sqlite=3.29.0
  - tk=8.6.9
  - toolz=0.10.0
  - tornado=6.0.3
  - urllib3=1.25.6
  - wcwidth=0.1.7
  - wheel=0.33.6
  - xz=5.2.4
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.0
  - pip:
    - absl-py==0.8.0
    - astor==0.8.0
    - click==7.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.24.0
    - h5py==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - opt-einsum==3.1.0
    - protobuf==3.9.2
    - six==1.12.0
    - tensorboard==2.0.0
    - tensorflow==2.0.0
    - tensorflow-estimator==2.0.0
    - termcolor==1.1.0
    - toml==0.10.0
    - werkzeug==0.16.0
    - wrapt==1.11.2

