site_name: Cookiecutter SemSeg
site_description: A project template and directory structure for Python semantic segmentation projects.
site_favicon: favicon.ico
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
